version: '3.8'

services:
  vben-admin:
    build:
      context: .
      dockerfile: scripts/deploy/Dockerfile
    image: vben-admin-local
    container_name: vben-admin
    ports:
      - "8010:8080"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3
